[project]
name = "maniqa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "einops",
    "logging",
    "numpy",
    "opencv-python",
    "pandas",
    "scipy>=1.16.3",
    "tensorboardx",
    "timm>=1.0.22",
    "torch",
    "torchsummary",
    "torchvision",
    "tqdm",
]

[tool.uv]
python-install-mirror = "https://registry.npmmirror.com/-/binary/python-build-standalone/"

[[tool.uv.index]]
url = "https://mirrors.ustc.edu.cn/pypi/simple"
default = true

[tool.ruff.lint]
# 1. Enable flake8-bugbear (`B`) rules, in addition to the defaults.
# select = ["E4", "E7", "E9", "F", "B"]

# 2. Avoid enforcing line-length violations (`E501`)
ignore = ["E741"]
extend-select = ["I"]


[tool.ty.rules]
# index-out-of-bounds = "ignore"
unresolved-attribute = "ignore"
no-matching-overload = "ignore"
call-non-callable = "ignore"
# non-subscriptable = "ignore"
# possibly-missing-attribute = "ignore"
